[project]
name = "hydra"
version = "0.1.0"
description = "Implementation of \"Hydra: Bidirectional State Space Models Through Generalized Matrix Mixers\""
readme = "README.md"
authors = [
    { name = "Hydra Authors" },
    { name = "Quinn Tucker" },
]
requires-python = ">=3.12"
dependencies = [
    "causal-conv1d>=1.2.0",
    "einops>=0.5.0",
    "mamba-ssm>=2.1.0",
    "mosaicml-streaming==0.4.1",
    "omegaconf>=2.2.3",
    "torch>=2.4.0",
    "transformers>=4.28.1",
]

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"
